product-reviews:
  post:
    rating:
      - NotBlank
      - Type:
          type: numeric
      - GreaterThanOrEqual:
          value: 1
      - LessThanOrEqual:
          value: 5
    summary:
          - NotBlank
          - Length:
              max: 255
    nickname:
          - NotBlank
          - Length:
              max: 255